### ISSUE TITLE
Auto-shrink for alltoallv

### ISSUE THREAD

**Issue by mshiryaev** [facebookresearch/param#24] opened 2021-06-26 00:37 UTC
Hello,

I am trying to run PARAM in replay mode with 2 ranks using the trace which was generated on larger number of ranks.
The trace contains different operations including alltoallv.

By default PARAM reports issue "Number of tensor splits not equal to group size"

Traceback (most recent call last):
  File "./commsTraceReplay.py", line 708, in <module>
    main()
  File "./commsTraceReplay.py", line 704, in main
    traceBench.runBench(comms_world_info, commsParams)
  File "./commsTraceReplay.py", line 567, in runBench
    self.benchTime(commsParams)
  File "./commsTraceReplay.py", line 483, in benchTime
    self.collectiveArgs, retFlag=True
  File "./param/train/comms/pt/pytorch_dist_backend.py", line 183, in all_to_allv
    async_op=collectiveArgs.asyncOp,
  File "torch/distributed/distributed_c10d.py", line 2386, in all_to_all_single
    work = group.alltoall_base(output, input, output_split_sizes, input_split_sizes, opts)
RuntimeError: Number of tensor splits not equal to group size

If I set "--auto-shrink" then PARAM doesn't report issue and seems do adjustments for smaller scale but now issue happens on transport level:
tl_ucp_coll.c:42   TL_UCP ERROR failure in send completion Message truncated

**Comment by kingchc** [comment] 2021-08-05 19:19
Thanks to @Sergei-Lebedev, this should get resolved in https://github.com/facebookresearch/param/pull/25. We will have another patch to handle it nicely if trace provides more info (e.g., world size). 

Closing it for now, please reopen this if the issue is not fixed.

**Closed by kingchc** 2021-08-05 19:19 UTC
